/**
 *
 * Jose Lugo-Martinez, jlugomar@indiana.edu
 * School of Informatics and Computing
 * Indiana University-Bloomington 
 *
 * Jul-30-2013
 *
 * Copyright (c) 2014 Jose Lugo-Martinez,
 * Vladimir Vacic, and Predrag Radivojac.
 *
 */

#ifndef __CONFIG_H__
#define __CONFIG_H__

#define DIGRAPHLET_SIZE 3
#define DIGRAPHLETS_TYPES 34		// Maximum number of n-digraphlets up to n=3.
#define DIGRAPHLET_TYPES_SIZE 63    // Unused
#define LOG_DIGRAPHLET_TYPES_SIZE 6	
#define ALPHABET_SIZE 31
#define LOG_ALPHABET_SIZE 5
#define ZERO_CHAR '@'
#define SIMILARITY_THRESHOLD 1.0

// Flags for setting best digraphlets combination.
#define DIGRAPHLETS_1 1 // If 1 use 1-digraphlets when counting, otherwise do not consider 1-digraphlets.
#define DIGRAPHLETS_2 1 // If 1 use 2-digraphlets when counting, otherwise do not consider 2-digraphlets.
#define DIGRAPHLETS_3 1 // If 1 use 3-digraphlets when counting, otherwise do not consider 3-digraphlets.

#define OUTPUT_FORMAT 2 // If 0 print kernel matrix in binary format (for efficient SVM^light), 
                        // If 1 print triangular kernel matrix to standard output, 
                        // Otherwise print to standard output.

#include <fstream>
#include <utility>
#include <list>
#include <map>
#include <vector>
using namespace std;

typedef unsigned long Key;

// Enhanced data structure to accommodate for label substitutions and edge insertions and deletions.
struct MismatchInfo
{
    float matches;						// Contains counts for exact non-isomorphic labeled digraphlets found.
    float mismatches;					// Contains counts for inexact non-isomorphic labeled digraphlets obtained by edge indels algorithm.
    map<Key, float> mismatchesGraph;	// Contains counts for each inexact non-isomorphic labeled digraphlet generated by label substitutions algorithm and satisfying SIMILARITY_THRESHOLD (defined above).
};

#endif
